#!/usr/bin/with-contenv sh

# Setup Git
git config --global credential.helper store
git config --global user.email "scott@scottmebberson.com"
git config --global user.name "Scott Mebberson"

# Setup credentials for Git
set-git-credentials.js `git remote get-url origin`

# Setup the Git Worktree
cd $GITHUB_WORKSPACE
git worktree add out gh-pages
