#!/usr/bin/node

'use strict';

// This file will update the Git Worktree definition to use a relative path,
// rather than an absolute path. On my development machine the path
// `/Users/smebberson/Developer/scott.mebberson.codes` exists, in the content
// of a GitHub Action, it doesn't.

const fs = require('fs');
const path = require('path');

const file = path.join('/', 'github', 'workspace', 'out', '.git');

fs.readFile(file, { encoding: 'UTF8' }, (err, content) => {

    if (err) {
        console.error(err);
        process.exit(1);
    }

    if (/\/Users\/smebberson\/Developer\/scott\.mebberson\.codes/.test(content)) {

        const updatedContent = content.replace('/Users/smebberson/Developer/scott.mebberson.codes', '..')
    
        fs.writeFile(file, updatedContent, (writeErr) => {
    
            if (writeErr) {
                console.error(writeErr);
                process.exit(1);
            }
    
        });

        return console.log('Updated to a relative path.');

    }

    return console.log('No update required.');

});