name: Build
on: [push]

jobs:
    build:
        if: ${{ github.ref != 'refs/heads/master' }}
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Setup yarn
              run: yarn install
            - name: Build
              run: yarn next build
    deploy:
        if: ${{ github.ref == 'refs/heads/master' }}
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Setup Yarn
              run: yarn install
            - name: Build
              run: yarn next build
            - name: Setup Git
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
              run: |
                  git config --local credential.helper store
                  git config --local user.email "scott@scottmebberson.com"
                  git config --local user.name "Scott Mebberson"
                  echo "https://$GITHUB_ACTOR:$GH_TOKEN@github.com/$GITHUB_REPOSITORY.git" > $HOME/.git-credentials
                  git worktree add $HOME/smc-out gh-pages
            - name: Export
              run: yarn next export
            - name: Publish
              run: |
                  rm -rf $HOME/smc-out/*
                  cp CNAME $HOME/smc-out
                  cp -rf out/* $HOME/smc-out
                  cd $HOME/smc-out
                  touch .nojekyll
                  git add .
                  git commit -m "Deploying commit $GITHUB_SHA to gh-pages 🚀"
                  git push --force origin gh-pages
