name: Build
on: [push]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Setup
              uses: ./.github/actions/setup
            - name: Build
              uses: ./.github/actions/next
