name: Build
on: [push]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Setup Node.js
              uses: actions/setup-node@v1
            - name: Get yarn cache
              id: yarn-cache
              run: echo "::set-output name=dir::$(yarn cache dir)"
            - name: Cache yarn
              uses: actions/cache@v1
              with:
                  path: ${{ steps.yarn-cache.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-
            - name: Cache node_modules
              uses: actions/cache@v1
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-node_modules-
            - name: Setup yarn
              run: yarn install
            - name: Build
              run: yarn next build
            - name: Archive .next
              uses: actions/upload-artifact@v1
              with:
                  name: next
                  path: .next
    deploy:
        if: github.ref == 'refs/heads/master'
        name: Deploy
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Setup Node.js
              uses: actions/setup-node@v1
            - name: Get yarn cache
              id: yarn-cache
              run: echo "::set-output name=dir::$(yarn cache dir)"
            - name: Cache yarn
              uses: actions/cache@v1
              with:
                  path: ${{ steps.yarn-cache.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-
            - name: Cache node_modules
              uses: actions/cache@v1
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-node_modules-
            - name: Setup Yarn
              run: yarn install
            - name: Download .next
              uses: actions/download-artifact@v1
              with:
                  name: next
                  path: .next
            - name: Setup Git
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
              run: |
                  git config --local credential.helper store
                  git config --local user.email "scott@scottmebberson.com"
                  git config --local user.name "Scott Mebberson"
                  echo "https://$GITHUB_ACTOR:$GH_TOKEN@github.com/$GITHUB_REPOSITORY.git" > $HOME/.git-credentials
                  git worktree add out gh-pages
            - name: Export
              run: yarn next export
            - name: Publish
              run: |
                  cp CNAME ./out
                  cd ./out
                  touch .nojekyll
                  git add .
                  git commit -m "Deploying commit $GITHUB_SHA to gh-pages 🚀"
                  git push origin gh-pages
